name: Publish Emu app to docker registry

env:
    regsitry: "ghcr.io"

on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths-ignore:
            - "**/README.md"
            - "docker-compose**"
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                architecture: [linux/amd64]
        defaults:
            run:
                working-directory: ./src
        steps:
            # get the latest version of the repository
            - name: Checkout
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3

            # get the package.json version
            - uses: martinbeentjes/npm-get-version-action@master
              name: Get backend version
              id: app-version
              with:
                  path: ./src

            - name: Print current versions
              run: echo Building bunnyrescue version ${{ steps.app-version.outputs.current-version }}

            # docker buildx setup
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up docker buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
              with:
                  buildkitd-flags: --debug
            - name: List available platforms
              run: echo ${{ steps.buildx.outputs.platforms }}

            # docker registry login
            - name: Login to GHCR Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.registry }}
                  username: ${{ secrets.GH_USER }}
                  password: ${{ secrets.GH_TOKEN }}
                  logout: false

            # docker build image and push to registry
            - name: Build and push to registry
              uses: docker/build-push-action@v3
              with:
                  context: "./src"
                  platforms: ${{ matrix.architecture}}
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: |
                      ${{env.registry}}/bunnyrescue/bunnyrescue-app:latest
                      ${{env.registry}}/bunnyrescue/bunnyrescue-app:${{steps.app-version.outputs.current-version}}
                  outputs: type=registry,registry.insecure=true
                  labels: |
                      author=${{github.actor}}
                      version=${{steps.app-version.outputs.current-version}}
